In [ ]:
# Install Transformer from HuggingFace
!pip install transformers

Steps:

1. Tokenize
2. Token IDs -> model
3. Model activations -> Probabilities (using Softmax)
4. Argmax of Probabilities 

In [1]:
model_name = 'ProsusAI/finbert'

In [5]:
# Sequence Classification model
from transformers import BertForSequenceClassification

In [ ]:
model = BertForSequenceClassification.from_pretrained(model_name)

In [ ]:
from transformers import BertTokenizer

tokenizer = BertTokenizer.from_pretrained(model_name)

In [22]:
# a news from an Yahoo Finance
text = ('Rebecca Rubin Mon, July 12, 2021, 1:14 AM DIS \+2.45\% By Rebecca Rubin LOS ANGELES, July 11, (Variety.com) - Disney and Marvel\'s superhero adventure "Black Widow" \\
captured a massive $80 million in its first weekend, crushing the benchmark for the biggest opening weekend since the pandemic. \\
In a first for the Marvel Cinematic Universe, the film opened simultaneously in theaters and on Disney Plus as part of the streaming service\'s Premier Access offering, \\
where subscribers can rent "Black Widow" for an extra $30. Disney reported that "Black Widow" generated more than $60 million "in Disney Plus Premier Access consumer spend \\
globally," marking the rare occasion in which a studio discloses revenues for digital rentals. Overseas, "Black Widow" collected $78 million in its debut, boosting its global box office \\
haul to $158 million. Disney didn\'t share viewership data for the previously released "Cruella" starring Emma Stone and the animated "Raya and the Last Dragon," \\
which also premiered simultaneously in theaters and on Disney Plus. It\'s unclear if Disney will continue to report digital rentals for the upcoming action adventure "Jungle Cruise," \\
which opens in cinemas and on Disney Plus on July 30. In a statement on Sunday morning, Disney\'s media and entertainment distribution chairman Kareem Daniel said \\
"\'Black Widow\'s\' strong performance this weekend affirms our flexible distribution strategy of making franchise films available in theaters for a true cinematic experience and, \\
as COVID concerns continue globally, providing choice to consumers who prefer to watch at home on Disney Plus."')

text


'Rebecca Rubin Mon, July 12, 2021, 1:14 AM DIS \\+2.45\\% By Rebecca Rubin LOS ANGELES, July 11, (Variety.com) - Disney and Marvel\'s superhero adventure "Black Widow" \\captured a massive $80 million in its first weekend, crushing the benchmark for the biggest opening weekend since the pandemic. \\In a first for the Marvel Cinematic Universe, the film opened simultaneously in theaters and on Disney Plus as part of the streaming service\'s Premier Access offering, \\where subscribers can rent "Black Widow" for an extra $30. Disney reported that "Black Widow" generated more than $60 million "in Disney Plus Premier Access consumer spend \\globally," marking the rare occasion in which a studio discloses revenues for digital rentals. Overseas, "Black Widow" collected $78 million in its debut, boosting its global box office \\haul to $158 million. Disney didn\'t share viewership data for the previously released "Cruella" starring Emma Stone and the animated "Raya and the Last Dragon," \\whi

In [23]:
tokens = tokenizer.encode_plus(text, 
                               max_length=512, # Maximum token size
                               truncation=True, # If tokens lenght > max_length: Truncate excess part
                               padding='max_length', # If tokens length < max_length: Pad token until == max_length
                               add_special_tokens=True,
                               return_tensors='pt', # Tensors: pytorch-> 'pt', tensorflow-> 'tf' or numpy tensors
                               )  


### BERT Special Toke IDs
[CLS] = 101

[SEP] = 102

[MASK] = 103

[UNK] = 100

[PAD] = 0

In [24]:
tokens

{'input_ids': tensor([[  101,  9423, 20524, 12256,  1010,  2251,  2260,  1010, 25682,  1010,
          1015,  1024,  2403,  2572,  4487,  2015,  1032,  1009,  1016,  1012,
          3429,  1032,  1003,  2011,  9423, 20524,  3050,  3349,  1010,  2251,
          2340,  1010,  1006,  3528,  1012,  4012,  1007,  1011,  6373,  1998,
          8348,  1005,  1055, 16251,  6172,  1000,  2304,  7794,  1000,  1032,
          4110,  1037,  5294,  1002,  3770,  2454,  1999,  2049,  2034,  5353,
          1010, 14527,  1996,  6847, 10665,  2005,  1996,  5221,  3098,  5353,
          2144,  1996,  6090,  3207,  7712,  1012,  1032,  1999,  1037,  2034,
          2005,  1996,  8348, 21014,  5304,  1010,  1996,  2143,  2441,  7453,
          1999, 12370,  1998,  2006,  6373,  4606,  2004,  2112,  1997,  1996,
         11058,  2326,  1005,  1055,  4239,  3229,  5378,  1010,  1032,  2073,
         17073,  2064,  9278,  1000,  2304,  7794,  1000,  2005,  2019,  4469,
          1002,  2382,  1012,  6373,  

#### without **kwargs
random_func(var1='hello', var2='world')

#### with **kwargs
input_dict = {var1='hello', var2='world'}

random_func(**input_dict)

In [25]:
output = model(**tokens)

In [26]:
output

SequenceClassifierOutput([('logits',
                           tensor([[ 1.9429, -2.3052, -0.6809]], grad_fn=<AddmmBackward>))])

In [27]:
output[0]

tensor([[ 1.9429, -2.3052, -0.6809]], grad_fn=<AddmmBackward>)

In [28]:
# Convert Output Activations into Probabilities
import torch.nn.functional as F
probs = F.softmax(output[0], dim=-1) # -1 means final dimension. If we don't specify the dimensions it'll give error
probs

tensor([[0.9201, 0.0132, 0.0667]], grad_fn=<SoftmaxBackward>)

In [29]:
import torch
# Get the maximum predicted class
pred = torch.argmax(probs)

In [30]:
pred.item()

0